root: true
env:
  browser: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
ignorePatterns:
  - dist
  - '**/*.typegen.ts'
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
plugins:
  - react-refresh
rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
  react-refresh/only-export-components:
    - warn
    - allowConstantExport: true
