/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 appartment_v1.gltf -t -K -T 
Files: appartment_v1.gltf [18.62MB] > appartment_v1-transformed.glb [1.69MB] (91%)
*/

import { useGLTF } from '@react-three/drei';
import { forwardRef } from 'react';
import * as THREE from 'three';
import { type GLTF } from 'three-stdlib';
import { barMachine } from '../../../machines/bar.machine';
import { toiletMachine } from '../../../machines/toilet.machine';
import { AppartmentHotspot } from './HotSpots/AppartmentHotspot';

type GLTFResult = GLTF & {
  nodes: {
    table: THREE.Mesh;
    bookshelf_2001: THREE.Mesh;
    wooden_floor3001: THREE.Mesh;
    bookshelf001: THREE.Mesh;
    DJ_1001: THREE.Mesh;
    boombox_large_1001: THREE.Mesh;
    render_map_brick003: THREE.Mesh;
    sofa_3001: THREE.Mesh;
    sofa_2001: THREE.Mesh;
    closet_without_chair001: THREE.Mesh;
    closet_chair001: THREE.Mesh;
    plant_4001: THREE.Mesh;
    plant_3001: THREE.Mesh;
    plant_2001: THREE.Mesh;
    plant_1001: THREE.Mesh;
    bar001: THREE.Mesh;
    graffitti_party: THREE.Mesh;
    graffitti_gamejam: THREE.Mesh;
    graffitti_react: THREE.Mesh;
    plant_5001: THREE.Mesh;
    plant_2002: THREE.Mesh;
    stool_4001: THREE.Mesh;
    stool_3001: THREE.Mesh;
    stool_2001: THREE.Mesh;
    stool_1001: THREE.Mesh;
    boombox_large_2001: THREE.Mesh;
    gueridon001: THREE.Mesh;
    lamp_1001: THREE.Mesh;
    armchair001: THREE.Mesh;
    skyline: THREE.Mesh;
    ['38_black_and_white_marble_tile_texture-seamless']: THREE.Mesh;
    cheloupee: THREE.Mesh;
    sink: THREE.Mesh;
    hand_dryer: THREE.Mesh;
    ['241_victorian_cement_floor_tile_uni_colour_texture-seamless']: THREE.Mesh;
    render_map_brick: THREE.Mesh;
    window002: THREE.Mesh;
    Cube001: THREE.Mesh;
  };
  materials: {
    table: THREE.MeshStandardMaterial;
    bookshelf_2: THREE.MeshStandardMaterial;
    wooden_floor3: THREE.MeshStandardMaterial;
    bookshelf: THREE.MeshStandardMaterial;
    DJ_1: THREE.MeshStandardMaterial;
    boombox_large_1: THREE.MeshStandardMaterial;
    render_map_brick: THREE.MeshStandardMaterial;
    sofa_3: THREE.MeshStandardMaterial;
    sofa_2: THREE.MeshStandardMaterial;
    closet_without_chair: THREE.MeshStandardMaterial;
    closet_chair: THREE.MeshStandardMaterial;
    ['plant_4.001']: THREE.MeshStandardMaterial;
    ['plant_3.001']: THREE.MeshStandardMaterial;
    ['plant_2.001']: THREE.MeshStandardMaterial;
    ['plant_1.001']: THREE.MeshStandardMaterial;
    bar: THREE.MeshStandardMaterial;
    graffitti_party: THREE.MeshStandardMaterial;
    graffitti_gamejam: THREE.MeshStandardMaterial;
    graffitti_react: THREE.MeshStandardMaterial;
    plant_5: THREE.MeshStandardMaterial;
    plant_2: THREE.MeshStandardMaterial;
    stool_4: THREE.MeshStandardMaterial;
    stool_3: THREE.MeshStandardMaterial;
    stool_2: THREE.MeshStandardMaterial;
    stool_1: THREE.MeshStandardMaterial;
    boombox_large_2: THREE.MeshStandardMaterial;
    gueridon: THREE.MeshStandardMaterial;
    lamp_1: THREE.MeshStandardMaterial;
    armchair: THREE.MeshStandardMaterial;
    skyline: THREE.MeshStandardMaterial;
    ['38_black and white marble tile texture-seamless']: THREE.MeshStandardMaterial;
    cheloupee: THREE.MeshStandardMaterial;
    sink: THREE.MeshStandardMaterial;
    hand_dryer: THREE.MeshStandardMaterial;
    ['241_victorian cement floor tile uni colour texture-seamless']: THREE.MeshStandardMaterial;
    window: THREE.MeshStandardMaterial;
  };
};

export const AppartmentModel = forwardRef<
  THREE.Mesh,
  JSX.IntrinsicElements['group']
>((props, ref) => {
  const { nodes, materials } = useGLTF(
    'assets/appartment_v1-transformed.glb',
  ) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh ref={ref}>
        <mesh
          geometry={nodes.table.geometry}
          material={materials.table}
          position={[29.321, 0.783, 6.673]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.909}
        />
        <mesh
          geometry={nodes.bookshelf_2001.geometry}
          material={materials.bookshelf_2}
          position={[19.725, 3.49, -0.612]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[7.57, 8.224, 8.224]}
        />
        <mesh
          geometry={nodes.wooden_floor3001.geometry}
          material={materials.wooden_floor3}
          position={[-0.591, -1.285, 4.169]}
          scale={42.046}
        />
        <mesh
          geometry={nodes.bookshelf001.geometry}
          material={materials.bookshelf}
          position={[33.14, 3.355, -1.367]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[7.566, 8.203, 8.203]}
        />
        <mesh
          geometry={nodes.DJ_1001.geometry}
          material={materials.DJ_1}
          position={[-2.301, 4.825, 1.024]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={5.446}
        />
        <mesh
          geometry={nodes.boombox_large_1001.geometry}
          material={materials.boombox_large_1}
          position={[-2.087, 1.309, 2.761]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={6.564}
        />
        <mesh
          geometry={nodes.render_map_brick003.geometry}
          material={materials.render_map_brick}
          position={[-30.955, 2.904, -34.581]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={7.181}
        />
        <mesh
          geometry={nodes.sofa_3001.geometry}
          material={materials.sofa_3}
          position={[19.332, 0.349, 15.097]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={3.034}
        />
        <mesh
          geometry={nodes.sofa_2001.geometry}
          material={materials.sofa_2}
          position={[-16.512, 0.247, 4.434]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={3.787}
        />
        <mesh
          geometry={nodes.closet_without_chair001.geometry}
          material={materials.closet_without_chair}
          position={[-29.346, 3.776, 1.324]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={11.616}
        />
        <mesh
          geometry={nodes.closet_chair001.geometry}
          material={materials.closet_chair}
          position={[-29.36, 4.963, 4.611]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={13.906}
        />
        <mesh
          geometry={nodes.plant_4001.geometry}
          material={materials['plant_4.001']}
          position={[-42.124, 1.108, 16.682]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={5.529}
        />
        <mesh
          geometry={nodes.plant_3001.geometry}
          material={materials['plant_3.001']}
          position={[-38.924, -0.016, 19.755]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={3.302}
        />
        <mesh
          geometry={nodes.plant_2001.geometry}
          material={materials['plant_2.001']}
          position={[-35.394, 1.884, 4.805]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={6.021}
        />
        <mesh
          geometry={nodes.plant_1001.geometry}
          material={materials['plant_1.001']}
          position={[-19.796, -0.295, 10.567]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.673}
        />

        <AppartmentHotspot
          geometry={nodes.bar001.geometry}
          materials={materials.bar}
          position={[8.725, 1.23, 7.158]}
          rotation={[-Math.PI / 2, 0, -0.191]}
          scale={-5.408}
          hotSpotMachine={barMachine}
        />

        <mesh
          geometry={nodes.graffitti_party.geometry}
          material={materials.graffitti_party}
          position={[-14.192, 6.328, -2.106]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={5.761}
        />
        <mesh
          geometry={nodes.graffitti_gamejam.geometry}
          material={materials.graffitti_gamejam}
          position={[-8.533, 9.614, -2.106]}
          rotation={[Math.PI / 2, -0.058, 0]}
          scale={3.36}
        />
        <mesh
          geometry={nodes.graffitti_react.geometry}
          material={materials.graffitti_react}
          position={[-16.49, 10.271, -1.151]}
          rotation={[Math.PI / 2, 0.119, 0]}
          scale={4.801}
        />
        <mesh
          geometry={nodes.plant_5001.geometry}
          material={materials.plant_5}
          position={[15.716, 1.347, 10.154]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.488}
        />
        <mesh
          geometry={nodes.plant_2002.geometry}
          material={materials.plant_2}
          position={[17.831, 1.788, 4.657]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={5.851}
        />
        <mesh
          geometry={nodes.stool_4001.geometry}
          material={materials.stool_4}
          position={[2.263, 0.17, 20.155]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.853}
        />
        <mesh
          geometry={nodes.stool_3001.geometry}
          material={materials.stool_3}
          position={[-0.083, 0.326, 17.737]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.305}
        />
        <mesh
          geometry={nodes.stool_2001.geometry}
          material={materials.stool_2}
          position={[-10.612, 0.277, 18.077]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={3.302}
        />
        <mesh
          geometry={nodes.stool_1001.geometry}
          material={materials.stool_1}
          position={[4.247, 0.302, 19.084]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.917}
        />
        <mesh
          geometry={nodes.boombox_large_2001.geometry}
          material={materials.boombox_large_2}
          position={[-13.736, 2.432, -1.869]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={7.806}
        />
        <mesh
          geometry={nodes.gueridon001.geometry}
          material={materials.gueridon}
          position={[-37.949, 1.769, -2.077]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={6.676}
        />
        <mesh
          geometry={nodes.lamp_1001.geometry}
          material={materials.lamp_1}
          position={[20.775, 0.565, 17.354]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={3.302}
        />
        <mesh
          geometry={nodes.armchair001.geometry}
          material={materials.armchair}
          position={[41.077, 1.563, 7.42]}
          rotation={[Math.PI / 2, 0, -3.13]}
          scale={4.602}
        />
        <mesh
          geometry={nodes.skyline.geometry}
          material={materials.skyline}
          position={[80.194, 2.863, -1.972]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={25.354}
        />
        <mesh
          geometry={
            nodes['38_black_and_white_marble_tile_texture-seamless'].geometry
          }
          material={
            materials['38_black and white marble tile texture-seamless']
          }
          position={[51.326, -0.712, 1.437]}
          scale={11.879}
        />

        <AppartmentHotspot
          geometry={nodes.cheloupee.geometry}
          materials={materials.cheloupee}
          position={[54.937, 3.299, -2.056]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.715}
          hotSpotMachine={toiletMachine}
        />
        <mesh
          geometry={nodes.sink.geometry}
          material={materials.sink}
          position={[48.333, 2.102, 4.6]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={5.64}
        />
        <mesh
          geometry={nodes.hand_dryer.geometry}
          material={materials.hand_dryer}
          position={[47.349, 8.925, 0.097]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.497}
        />
        <mesh
          geometry={
            nodes['241_victorian_cement_floor_tile_uni_colour_texture-seamless']
              .geometry
          }
          material={
            materials[
              '241_victorian cement floor tile uni colour texture-seamless'
            ]
          }
          position={[-31.655, -0.982, 6.017]}
          scale={17.741}
        />
        <instancedMesh
          args={[
            nodes.render_map_brick.geometry,
            materials.render_map_brick,
            8,
          ]}
          // @ts-ignore
          instanceMatrix={nodes.render_map_brick.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.window002.geometry, materials.window, 7]}
          // @ts-ignore
          instanceMatrix={nodes.window002.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.Cube001.geometry, nodes.Cube001.material, 8]}
          // @ts-ignore
          instanceMatrix={nodes.Cube001.instanceMatrix}
        />
      </mesh>
    </group>
  );
});

useGLTF.preload('assets/appartment_v1-transformed.glb');
